### ISSUE TITLE
Λείπει η trim() στο window.getSelection().toString()

### ISSUE THREAD

**Issue by spacevoyager78** [ale3andro/simple_html5_games#2]
Στα index3.html, index4.html, index4a.html, index4b.html και index4c.html εκεί που υπάρχει:
`window.getSelection().toString()`
χρειάζεται να γίνει:
`window.getSelection().toString().trim()`
γιατί με το διπλό κλικ επιλέγονται και τα κενά πριν ή μετά από τις λέξεις, οπότε ο έλεγχος το βγάζει λάθος.

**Comment by ale3andro** [comment]
Καλησπέρα,
για να πω την αλήθεια δεν αντιμετώπισα ποτέ πρόβλημα χωρίς το trim() και το χρησιμοποιώ αρκετό καιρό. Με διπλό κλικ, o firefox τουλάχιστον, επιλέγει μόνο την λέξη και όχι τα κενά που προηγούνται ή έπονται. Επειδή αυτά τα παιχνίδια είναι για Α και Β τάξη, σε αυτές τις τάξεις παροτρύνω τους μαθητές μου να χρησιμοποιούν διπλό κλικ για επιλογή λέξης (στο μέσο της λέξης) αντί για drag με πατημένο το αριστερό κουμπί του ποντικού.
Σε κάθε περίπτωση θα το προσθέσω, γιατί ακόμη και αν κάποιο παιδί 6-7 χρονών επιλέξει και ένα κενό, καλό θα είναι να ανταμειφθεί για την δεξιότητα χειρισμού ποντικιού που επέδειξε!

**Comment by spacevoyager78** [comment]
Σε μένα σε Windows 10 και ο Firefox και ο Edge με διπλό κλικ στη μέση της λέξης επιλέγουν και το κενό μετά αυτόματα, γι' αυτό στο έγραψα...

**Comment by ale3andro** [comment]
Ευχαριστώ, η αλήθεια είναι ότι δεν θυμάμαι να το έχω δοκιμάσει ποτέ σε Windows. 
Ελπίζω να το βρεις χρήσιμο. Στα μικρά μου αρέσουν αυτού του τύπου τα παιχνίδια και τους βοηθούν να βελτιώνουν τη δεξιότητα τους με το ποντίκι.
